# Generated by Django 5.2.10 on 2026-02-24 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shelfentry_delete_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfentry',
            name='curr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='read_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelfentry',
            name='want_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
